replicaCount: 1

image:
  repository: 
  tag: 
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi

ResourceQuota:
  limits:
    cpu: 6
    memory: 6Gi

hpa:
  enabled: true
  maxReplicas: 4
  CpuPercentage: 100

livenessProbe:
  httpGet:
    path: /health
    port: 5000

readinessProbe:
  httpGet:
    path: /health
    port: 5000
    
ingress:
  enabled: true
  istio: true
  alb:
    enabled: false
    scheme: internet-facing
    hostBased: false
    path: "/"
    healthcheckPath: /health
    http2:
      enabled: true
      maxConcurrentStreams: 128
    annotations: {}
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "*"
      paths: []
  url:
    prefix:
    prefixOverwrite:
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

rbac:
  enabled: true

service:
  type: ClusterIP
  ports:
  - port: 5000
    name: http
    protocol: TCP
    
    
