apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  appsettings.json: |-    
{{ printf "%s/appsettings.json" .Values.valuesPath | .Files.Get | indent 4 }}