{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.istio -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  {{- range .Values.ingress.hosts }}
  - "{{ .host }}"
  {{- end }}
  gateways:
  - gateways/mirae-gateway
  http:
  - match:
    - uri:
        prefix: {{ (.Values.ingress.url.prefixOverwrite | default .Values.ingress.url.prefix) }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
        {{- with (first .Values.service.ports) }}
          number: {{ .port }}
        {{- end }}
{{- end }}
{{- end }}