apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
{{- with .Values.serviceaccount }}
  annotations:
{{  .annotations | default dict | toYaml | indent 4 }}
{{- end }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
