apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    filebeat: "true"
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      filebeat: "true"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        filebeat: "true"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | trim | nindent 12 -}}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | trim | nindent 12 -}}
          {{- end }}          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
          ports:
            {{- with (first .Values.service.ports) }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          {{- if .Values.env }}
          env:         
          {{- toYaml .Values.env | nindent 12 -}}
          {{- end }}
          {{- if .Values.valuesPath }}
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: "/app/appsettings.json"
              readOnly: true
              subPath: "appsettings.json"
          {{- end -}}
          {{- if .Values.volumeMounts }}
          {{- toYaml .Values.volumeMounts | nindent 12 }} 
          {{- end -}}
      {{- if .Values.valuesPath }}
      volumes:
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
      {{- end -}}
      {{- if .Values.volumes }}
      {{- toYaml .Values.volumes | nindent 8 }} 
      {{- end -}}




