{{- if or .Values.ingress.alb.enabled (and .Values.ingress.enabled (not .Values.ingress.istio)) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.alb.scheme | default "internet-facing" }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.alb.healthcheckPath | default "/health" }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.alb.subnets | join "," }}
    alb.ingress.kubernetes.io/load-balancer-attributes: |
      routing.http.xff_header_processing.mode=append,
      routing.http.xff_client_port.enabled=false,
      routing.http2.enabled={{ .Values.ingress.alb.http2.enabled | default true }},
      routing.http2.max_concurrent_streams={{ .Values.ingress.alb.http2.maxConcurrentStreams | default 128 }}
    {{- with .Values.ingress.alb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- if .Values.ingress.alb.hostBased }}
    - host: {{ .Values.ingress.alb.host }}
      http:
        paths:
          - path: {{ .Values.ingress.alb.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
    {{- else }}
    - http:
        paths:
          - path: {{ .Values.ingress.alb.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
    {{- end }}
{{- end }}