apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
{{  .Values.service.annotations | default dict | toYaml | indent 4 }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 2 }} 
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}


