valuesPath: Homolog
env:
  - name: ASPNETCORE_URLS
    value: "#{VarASPURLS}#"
  - name: ASPNETCORE_ENVIRONMENT
    value: #{VarHmlAspEnv}#
  - name: COMPlus_EnableDiagnostics
    value: "#{VarComPlus}#" 
  - name: JWT_SECURITY_KEY
    value: #{VarJWT}#
    
hpa:
  enabled: false

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi

ResourceQuota:
  limits:
    cpu: 1
    memory: 2Gi

ingress:
  enabled: false
  istio: false
  alb:
    enabled: true
    scheme: internet-facing
    certificateArn: arn:aws:acm:us-east-1:369977587964:certificate/dedac4c6-1167-4e45-b768-99519d3dde78
    hostBased: true
    host: bff-mobile-homolog.miraeinvest.com.br
    healthcheckPath: /health
    subnets:
      - subnet-0c69edc54aeed59a4
      - subnet-01b8cb55647a02fb0
    annotations: {}  
  
service:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https