valuesPath: Development
env:
  - name: ASPNETCORE_URLS
    value: "#{VarASPURLS}#"
  - name: ASPNETCORE_ENVIRONMENT
    value: #{VarDevAspEnv}#
  - name: COMPlus_EnableDiagnostics
    value: "#{VarComPlus}#" 
  - name: JWT_SECURITY_KEY
    value: #{VarJWT}#
    
hpa:
  enabled: false

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi

ResourceQuota:
  limits:
    cpu: 1
    memory: 2Gi