{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.istio -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - "*"
  gateways:
  - gateways/mirae-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.ingress.url.prefix }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
{{- end }}