---
variables:
- group: ValueDev
- group: ValueHML
- group: ValuePRD

name: '0.0.0-rc.$(Build.BuildID)'

trigger:
  branches:
    include: ["develop","hotfix/*","release/*"]
pool:
 name: Azure Pipelines
resources:
  repositories:
    - repository: templates
      type: git
      name: "Mirae Digital/devops-templates"
      ref: refs/heads/feature/alb

stages:
  - stage: GetVersion
    jobs:
      - job: Migration
        displayName: Get Version from Csproj
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $xml = [Xml] (Get-Content .\src\MiraeDigital.BffMobile.API\MiraeDigital.BffMobile.API.csproj)
                $version = $xml.Project.PropertyGroup.Version
                echo $version
                echo "##vso[build.updatebuildnumber]$version-rc.$(Build.BuildID)"
  - template: build/docker.yaml@templates
    parameters:
      runSonar: false
      sonarProject: 'bff-mobile'
      solution: 'MiraeDigital.BffMobile.sln'
      image: 'bff-mobile'
